---
###########################
###########################
## Linter GitHub Actions ##
###########################
###########################
name: Unit tests

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on:
  push: {}
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [master]

###############
# Set the Job #
###############
jobs:
  test:
    # Name the Job
    name: Run unit tests
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup minimum Go version
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16.0' # The Go version to download (if necessary) and use.
      - name: Run tests
        run: go test ./...
...
